# Generated by Django 3.0.6 on 2020-05-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer_wall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
