# Generated by Django 3.0.6 on 2020-05-16 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayer_wall', '0002_auto_20200514_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_name',
        ),
    ]
